"""Generate docs/openapi.yaml from the Fastify route files plus a small annotation table.

Run: python3 docs/scripts/gen_openapi.py
"""
import re, glob, yaml

routes = []
for f in sorted(glob.glob("backend/src/http/routes/*.ts")):
    tag = f.split("/")[-1].removesuffix(".ts")
    src = open(f).read()
    for m in re.finditer(r'app\.(get|post|put|patch|delete)\("([^"]+)"(, \{ config: \{ auth: "(\w+)"| *, *admin)?', src):
        method, path, _, auth = m.group(1), m.group(2), m.group(3), m.group(4)
        if path.startswith("/admin"):
            auth = "admin"
        routes.append((method, path, auth or "user", tag))

BODIES = {
    ("post", "/auth/signup"): {"email": "string", "password": "string", "acceptTerms": "boolean"},
    ("post", "/auth/login"): {"email": "string", "password": "string"},
    ("post", "/auth/verify-email"): {"token": "string"},
    ("post", "/auth/mfa/verify"): {"code": "string", "enable": "boolean"},
    ("post", "/profile"): {"label": "string", "relationship": "string", "authorizationStatement": "string", "attest": "boolean", "jurisdictionCode": "string", "defaultApprovalMode": "string"},
    ("patch", "/profile/:id"): {"label": "string", "jurisdictionCode": "string", "defaultApprovalMode": "string", "blanketAuthorization": "boolean", "monitoringIntervalDays": "integer", "monitoringEnabled": "boolean", "useRelayEmail": "boolean"},
    ("post", "/profile/:id/identifiers"): {"type": "string", "value": "string", "isPrevious": "boolean"},
    ("post", "/removals"): {"recordId": "string"},
    ("post", "/removals/:id/approve"): {"subject": "string", "body": "string"},
    ("post", "/removals/:id/action"): {"choice": "string"},
    ("post", "/monitoring"): {"recordId": "string", "intervalDays": "integer", "enabled": "boolean"},
    ("put", "/sources/:sourceId/preference"): {"approvalMode": "string"},
    ("put", "/settings"): {"notifyEmail": "boolean", "notifyPush": "boolean", "notifyInApp": "boolean", "recordRetentionDays": "integer"},
    ("delete", "/account"): {"password": "string", "confirm": "string"},
    ("post", "/billing/change-plan"): {"plan": "string"},
    ("post", "/abuse-reports"): {"category": "string", "description": "string", "contact": "string"},
    ("post", "/inbound-email"): {"to": "string", "from": "string", "subject": "string", "text": "string"},
}

paths = {}
for method, path, auth, tag in routes:
    oapath = "/api" + re.sub(r":(\w+)", r"{\1}", path)
    op = {"tags": [tag], "operationId": f"{method}_{re.sub(r'[^a-zA-Z0-9]+', '_', path).strip('_')}",
          "responses": {"200": {"description": "OK"}, "4XX": {"$ref": "#/components/responses/Error"}}}
    params = [{"name": p, "in": "path", "required": True, "schema": {"type": "string"}} for p in re.findall(r":(\w+)", path)]
    if params:
        op["parameters"] = params
    if auth == "public":
        op["security"] = []
    elif auth == "admin":
        op["description"] = "Requires role=admin and an MFA-verified session."
    body = BODIES.get((method, path))
    if body:
        op["requestBody"] = {"required": True, "content": {"application/json": {"schema": {"type": "object", "properties": {k: {"type": v} for k, v in body.items()}}}}}
    paths.setdefault(oapath, {})[method] = op

spec = {
    "openapi": "3.1.0",
    "info": {"title": "Deep Scrubber API", "version": "0.1.0",
             "description": "Authorized personal-data discovery, removal, verification and monitoring. See docs/api.md for semantics."},
    "servers": [{"url": "http://localhost:4000"}],
    "security": [{"session": [], "csrf": []}],
    "components": {
        "securitySchemes": {
            "session": {"type": "apiKey", "in": "cookie", "name": "ds_session"},
            "csrf": {"type": "apiKey", "in": "header", "name": "x-csrf-token", "description": "Required on non-GET requests."},
        },
        "responses": {"Error": {"description": "Error", "content": {"application/json": {"schema": {
            "type": "object", "properties": {"error": {"type": "object", "properties": {
                "code": {"type": "string"}, "message": {"type": "string"}, "details": {"type": "object"}}}}}}}}},
    },
    "paths": dict(sorted(paths.items())),
}
with open("docs/openapi.yaml", "w") as f:
    f.write("# Generated by docs/scripts/gen_openapi.py — do not edit by hand.\n")
    yaml.safe_dump(spec, f, sort_keys=False, width=120)
print(f"{len(routes)} operations")
